### PR TITLE
add new required fields to Clan model

### PR DESCRIPTION
**Pull request by MikhailDeriabin**
1. Add ageRange, goals, phrase, language fields to Clan DTOs and schema
2. Update swagger accordingly
3. Remove `gameCoins` field from Clan creation and updating DTOs, since player should not be able to update them

### CODE REVIEW

**Review by leolabdev — APPROVED** [review]
nice update , it used to be weird to hardcode this value on the frontend

**Comment by leolabdev** [comment]
@MikhailDeriabin Will this update be deployed soon?

**Comment by MikhailDeriabin** [comment]
@leolabdev 

I am not sure, but I think it is already in dev build (dev.altzone.fi)

**Comment by MikhailDeriabin** [comment]
@leolabdev 

Now the newest version is on server devapi.altzone.fi. Although, some old clans can be without those fields and points and coins are all zeroes, because some changes need to be made in the game first.

**Pull request merged**
